[package]
name = "rust-mat-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
num-traits = "0.2.15"
rand = "0.8.4"
serde = "1.0.155"
